package constants

const (
	MONTHLY_TREND_IND = "MONTHLYTREND"
	YEARLY_TREND_IND  = "YEARLYTREND"
	QUAT_TREND_IND    = "QUARTERLYTREND"
	TOTAL_REVENUE_IND = "TOTALREV"
	PRODUCT_WISE_IND  = "PRODUCTWISE"
	CATEGORY_WISE_IND = "CATEGORYWISE"
	REGION_IND        = "REGIONWISE"
)
